(defpackage #:cl-graphicsmagick
  (:use #:cl #:cffi)
  (:nicknames :cl-gm :gm)
  (:export #:magick-get-version

           ;;; conditions
           #:magick-error
           #:magick-warning
           #:magick-get-exception
           #:pixel-get-exception

           ;;; utilities macros
           #:with-new-magick-wand
           #:with-magick-wand
           #:with-pixel-wand
           #:with-pixel-wands
           #:with-drawing-wand

           ;;; utilities functions
           #:image-width-height
           #:image-width
           #:image-height
           #:describe-image
           #:image-size
           #:magick-read-image-x
           #:image-format
           #:image-depth
           #:image-resolution
           #:image-gamma
           #:rotate-image
           #:flip-image
           #:add-text-watermark-to-image
           #:add-text-watermarks-to-image
           #:add-text-watermark
           #:add-text-watermarks
           #:adaptive-threadshold-image
           #:fit-width-height
           #:image-fit-width-height
           #:resize-image
           #:sample-image
           #:scale-image
           #:crop-image
           #:compress-image
           #:gif-cover
           #:gif-decompose
           #:compare-images
           #:composite-image
           #:contrast-image
           #:query-formats
           #:query-fonts

           ;;; Low level functions
           #:%InitializeMagick
           ;; magick_wand functions
           #:%CloneMagickWand
           #:%DestroyMagickWand
           #:%MagickAdaptiveThresholdImage
           #:%MagickAddImage
           #:%MagickAddNoiseImage
           #:%MagickAffineTransformImage
           #:%MagickAnnotateImage
           #:%MagickAnimateImages
           #:%MagickAppendImages
           #:%MagickAutoOrientImage
           #:%MagickAverageImages
           #:%MagickBlackThresholdImage
           #:%MagickBlurImage
           #:%MagickBorderImage
           #:%MagickCdlImage
           #:%MagickCharcoalImage
           #:%MagickChopImage
           #:%MagickClearException
           #:%MagickClipImage
           #:%MagickClipPathImage
           #:%MagickCoalesceImages
           #:%MagickColorFloodfillImage
           #:%MagickColorizeImage
           #:%MagickCommentImage
           #:%MagickCompareImageChannels
           #:%MagickCompareImages
           #:%MagickCompositeImage
           #:%MagickContrastImage
           #:%MagickConvolveImage
           #:%MagickCropImage
           #:%MagickCycleColormapImage
           #:%MagickDeconstructImages
           #:%MagickDescribeImage
           #:%MagickDespeckleImage
           #:%MagickDisplayImage
           #:%MagickDisplayImages
           #:%MagickDrawImage
           #:%MagickEdgeImage
           #:%MagickEmbossImage
           #:%MagickEnhanceImage
           #:%MagickEqualizeImage
           #:%MagickExtentImage
           #:%MagickFlattenImages
           #:%MagickFlipImage
           #:%MagickFlopImage
           #:%MagickFrameImage
           #:%MagickFxImage
           #:%MagickFxImageChannel
           #:%MagickGammaImage
           #:%MagickGammaImageChannel
           #:%MagickGetConfigureInfo ;; WARN: it's useless, only return NIL
           #:%MagickGetCopyright
           #:%MagickGetException
           #:%MagickGetFilename
           #:%MagickGetHomeURL
           #:%MagickGetImage
           #:%MagickGetImageAttribute
           #:%MagickGetImageBackgroundColor
           #:%MagickGetImageBluePrimary
           #:%MagickGetImageBorderColor
           #:%MagickGetImageBoundingBox
           #:%MagickGetImageChannelDepth
           #:%MagickGetImageChannelExtrema
           #:%MagickGetImageChannelMean
           #:%MagickGetImageColormapColor
           #:%MagickGetImageColors
           #:%MagickGetImageColorspace
           #:%MagickGetImageCompose
           #:%MagickGetImageCompression
           #:%MagickGetImageDelay
           #:%MagickGetImageDepth
           #:%MagickGetImageExtrema
           #:%MagickGetImageDispose
           #:%MagickGetImageFilename
           #:%MagickGetImageFormat
           #:%MagickGetImageFuzz
           #:%MagickGetImageGamma
           #:%MagickGetImageGeometry
           #:%MagickGetImageGravity
           #:%MagickGetImageGreenPrimary
           #:%MagickGetImageHeight
           #:%MagickGetImageHistogram
           #:%MagickGetImageIndex
           #:%MagickGetImageInterlaceScheme
           #:%MagickGetImageIterations
           #:%MagickGetImageMatte
           #:%MagickGetImageMatteColor
           #:%MagickGetImageOrientation
           #:%MagickGetImagePage
           #:%MagickGetImagePixels
           #:%MagickGetImageProfile
           #:%MagickGetImageRedPrimary
           #:%MagickGetImageRenderingIntent
           #:%MagickGetImageResolution
           #:%MagickGetImageScene
           #:%MagickGetImageSignature
           #:%MagickGetImageSize
           #:%MagickGetImageType
           #:%MagickGetImageSavedType
           #:%MagickGetImageUnits
           #:%MagickGetImageVirtualPixelMethod
           #:%MagickGetImageWhitePoint
           #:%MagickGetImageWidth
           #:%MagickGetNumberImages
           #:%MagickGetPackageName
           #:%MagickGetQuantumDepth
           #:%MagickGetReleaseDate
           #:%MagickGetResourceLimit
           #:%MagickGetSamplingFactors
           #:%MagickGetSize
           #:%MagickGetVersion
           #:%MagickHaldClutImage
           #:%MagickHasNextImage
           #:%MagickHasPreviousImage
           #:%MagickImplodeImage
           #:%MagickLabelImage
           #:%MagickLevelImage
           #:%MagickLevelImageChannel
           #:%MagickMagnifyImage
           #:%MagickMapImage
           #:%MagickMatteFloodfillImage
           #:%MagickMedianFilterImage
           #:%MagickMinifyImage
           #:%MagickModulateImage
           #:%MagickMontageImage
           #:%MagickMorphImages
           #:%MagickMosaicImages
           #:%MagickMotionBlurImage
           #:%MagickNegateImage
           #:%MagickNegateImageChannel
           #:%MagickNextImage
           #:%MagickNormalizeImage
           #:%MagickOilPaintImage
           #:%MagickOpaqueImage
           #:%MagickOperatorImageChannel
           #:%MagickPingImage
           #:%MagickPreviewImages
           #:%MagickPreviousImage
           #:%MagickProfileImage
           #:%MagickQuantizeImage
           #:%MagickQuantizeImages
           #:%MagickQueryFontMetrics
           #:%MagickQueryFonts
           #:%MagickQueryFormats
           #:%MagickRadialBlurImage
           #:%MagickRaiseImage
           #:%MagickReadImage
           #:%MagickReadImageBlob
           #:%MagickReadImageFile
           #:%MagickReduceNoiseImage
           #:%MagickRelinquishMemory
           #:%MagickRemoveImage
           #:%MagickRemoveImageOption
           #:%MagickRemoveImageProfile
           #:%MagickResetIterator
           #:%MagickResampleImage
           #:%MagickResizeImage
           #:%MagickRollImage
           #:%MagickRotateImage
           #:%MagickSampleImage
           #:%MagickScaleImage
           #:%MagickSeparateImageChannel
           #:%MagickSetCompressionQuality
           #:%MagickSetDepth
           #:%MagickSetFilename
           #:%MagickSetFormat
           #:%MagickSetImage
           #:%MagickSetImageAttribute
           #:%MagickSetImageBackgroundColor
           #:%MagickSetImageBluePrimary
           #:%MagickSetImageBorderColor
           #:%MagickSetImageColormapColor
           #:%MagickSetImageColorspace
           #:%MagickSetImageCompose
           #:%MagickSetImageCompression
           #:%MagickSetImageDelay
           #:%MagickSetImageChannelDepth
           #:%MagickSetImageDepth
           #:%MagickSetImageDispose
           #:%MagickSetImageFilename
           #:%MagickSetImageFormat
           #:%MagickSetImageFuzz
           #:%MagickSetImageGamma
           #:%MagickSetImageGeometry
           #:%MagickSetImageGravity
           #:%MagickSetImageGreenPrimary
           #:%MagickSetImageIndex
           #:%MagickSetImageInterlaceScheme
           #:%MagickSetImageIterations
           #:%MagickSetImageMatte
           #:%MagickSetImageMatteColor
           #:%MagickSetImageOption
           #:%MagickSetImageOrientation
           #:%MagickSetImagePage
           #:%MagickSetImagePixels
           #:%MagickSetImageProfile
           #:%MagickSetImageRedPrimary
           #:%MagickSetImageRenderingIntent
           #:%MagickSetImageResolution
           #:%MagickSetImageScene
           #:%MagickSetImageType
           #:%MagickSetImageSavedType
           #:%MagickSetImageUnits
           #:%MagickSetImageVirtualPixelMethod
           #:%MagickSetInterlaceScheme
           #:%MagickSetResolution
           #:%MagickSetResolutionUnits
           #:%MagickSetResourceLimit
           #:%MagickSetSamplingFactors
           #:%MagickSetSize
           #:%MagickSetImageWhitePoint
           #:%MagickSetPassphrase
           #:%MagickSharpenImage
           #:%MagickShaveImage
           #:%MagickShearImage
           #:%MagickSolarizeImage
           #:%MagickSpreadImage
           #:%MagickSteganoImage
           #:%MagickStereoImage
           #:%MagickStripImage
           #:%MagickSwirlImage
           #:%MagickTextureImage
           #:%MagickThresholdImage
           #:%MagickThresholdImageChannel
           #:%MagickTintImage
           #:%MagickTransformImage
           #:%MagickTransparentImage
           #:%MagickTrimImage
           #:%MagickUnsharpMaskImage
           #:%MagickWaveImage
           #:%MagickWhiteThresholdImage
           #:%MagickWriteImage
           #:%MagickWriteImagesFile
           #:%MagickWriteImageBlob
           #:%MagickWriteImageFile
           #:%MagickWriteImages
           #:%NewMagickWand

           ;;; drawing_wand functions
           #:%MagickCloneDrawingWand
           #:%MagickDestroyDrawingWand
           #:%MagickDrawAnnotation
           #:%MagickDrawAffine
           #:%MagickDrawAllocateWand
           #:%MagickDrawArc
           #:%MagickDrawBezier
           #:%MagickDrawCircle
           #:%MagickDrawClearException
           #:%MagickDrawGetClipPath
           #:%MagickDrawSetClipPath
           #:%MagickDrawGetClipRule
           #:%MagickDrawSetClipRule
           #:%MagickDrawGetClipUnits
           #:%MagickDrawGetException
           #:%MagickDrawSetClipUnits
           #:%MagickDrawColor
           #:%MagickDrawComment
           #:%MagickDrawEllipse
           #:%MagickDrawGetFillColor
           #:%MagickDrawSetFillColor
           #:%MagickDrawSetFillPatternURL
           #:%MagickDrawGetFillOpacity
           #:%MagickDrawSetFillOpacity
           #:%MagickDrawGetFillRule
           #:%MagickDrawSetFillRule
           #:%MagickDrawGetFont
           #:%MagickDrawSetFont
           #:%MagickDrawGetFontFamily
           #:%MagickDrawSetFontFamily
           #:%MagickDrawGetFontSize
           #:%MagickDrawSetFontSize
           #:%MagickDrawGetFontStretch
           #:%MagickDrawSetFontStretch
           #:%MagickDrawGetFontStyle
           #:%MagickDrawSetFontStyle
           #:%MagickDrawGetFontWeight
           #:%MagickDrawSetFontWeight
           #:%MagickDrawGetGravity
           #:%MagickDrawSetGravity
           #:%MagickDrawComposite
           #:%MagickDrawLine
           #:%MagickDrawMatte
           #:%MagickDrawPathClose
           #:%MagickDrawPathCurveToAbsolute
           #:%MagickDrawPathCurveToRelative
           #:%MagickDrawPathCurveToQuadraticBezierAbsolute
           #:%MagickDrawPathCurveToQuadraticBezierRelative
           #:%MagickDrawPathCurveToQuadraticBezierSmoothAbsolute
           #:%MagickDrawPathCurveToQuadraticBezierSmoothRelative
           #:%MagickDrawPathCurveToSmoothAbsolute
           #:%MagickDrawPathCurveToSmoothRelative
           #:%MagickDrawPathEllipticArcAbsolute
           #:%MagickDrawPathEllipticArcRelative
           #:%MagickDrawPathFinish
           #:%MagickDrawPathLineToAbsolute
           #:%MagickDrawPathLineToRelative
           #:%MagickDrawPathLineToHorizontalAbsolute
           #:%MagickDrawPathLineToHorizontalRelative
           #:%MagickDrawPathLineToVerticalAbsolute
           #:%MagickDrawPathLineToVerticalRelative
           #:%MagickDrawPathMoveToAbsolute
           #:%MagickDrawPathMoveToRelative
           #:%MagickDrawPathStart
           #:%MagickDrawPeekGraphicContext
           #:%MagickDrawPoint
           #:%MagickDrawPolygon
           #:%MagickDrawPolyline
           #:%MagickDrawPopClipPath
           #:%MagickDrawPopDefs
           #:%MagickDrawPopGraphicContext
           #:%MagickDrawPopPattern
           #:%MagickDrawPushClipPath
           #:%MagickDrawPushDefs
           #:%MagickDrawPushGraphicContext
           #:%MagickDrawPushPattern
           #:%MagickDrawRectangle
           #:%MagickDrawRender
           #:%MagickDrawRotate
           #:%MagickDrawRoundRectangle
           #:%MagickDrawScale
           #:%MagickDrawSkewX
           #:%MagickDrawSkewY
           #:%MagickDrawGetStrokeColor
           #:%MagickDrawSetStrokeColor
           #:%MagickDrawSetStrokePatternURL
           #:%MagickDrawGetStrokeAntialias
           #:%MagickDrawSetStrokeAntialias
           #:%MagickDrawGetStrokeDashArray
           #:%MagickDrawSetStrokeDashArray
           #:%MagickDrawGetStrokeDashOffset
           #:%MagickDrawSetStrokeDashOffset
           #:%MagickDrawGetStrokeLineCap
           #:%MagickDrawSetStrokeLineCap
           #:%MagickDrawGetStrokeLineJoin
           #:%MagickDrawSetStrokeLineJoin
           #:%MagickDrawGetStrokeMiterLimit
           #:%MagickDrawSetStrokeMiterLimit
           #:%MagickDrawGetStrokeOpacity
           #:%MagickDrawSetStrokeOpacity
           #:%MagickDrawGetStrokeWidth
           #:%MagickDrawSetStrokeWidth
           #:%MagickDrawGetTextAntialias
           #:%MagickDrawSetTextAntialias
           #:%MagickDrawGetTextDecoration
           #:%MagickDrawSetTextDecoration
           #:%MagickDrawGetTextEncoding
           #:%MagickDrawSetTextEncoding
           #:%MagickDrawGetTextUnderColor
           #:%MagickDrawSetTextUnderColor
           #:%MagickDrawTranslate
           #:%MagickDrawSetViewbox
           #:%MagickNewDrawingWand

           ;;; pixel_wand functions
           #:%ClonePixelWand
           #:%ClonePixelWands
           #:%DestroyPixelWand
           #:%NewPixelWand
           #:%NewPixelWands
           #:%PixelGetException
           #:%PixelGetBlack
           #:%PixelGetBlackQuantum
           #:%PixelGetBlue
           #:%PixelGetBlueQuantum
           #:%PixelGetColorAsString
           #:%PixelGetColorCount
           #:%PixelGetCyan
           #:%PixelGetCyanQuantum
           #:%PixelGetGreen
           #:%PixelGetGreenQuantum
           #:%PixelGetMagenta
           #:%PixelGetMagentaQuantum
           #:%PixelGetOpacity
           #:%PixelGetOpacityQuantum
           #:%PixelGetQuantumColor
           #:%PixelGetRed
           #:%PixelGetRedQuantum
           #:%PixelGetYellow
           #:%PixelGetYellowQuantum
           #:%PixelSetBlack
           #:%PixelSetBlackQuantum
           #:%PixelSetBlue
           #:%PixelSetBlueQuantum
           #:%PixelSetColor
           #:%PixelSetColorCount
           #:%PixelSetCyan
           #:%PixelSetCyanQuantum
           #:%PixelSetGreen
           #:%PixelSetGreenQuantum
           #:%PixelSetMagenta
           #:%PixelSetMagentaQuantum
           #:%PixelSetOpacity
           #:%PixelSetOpacityQuantum
           #:%PixelSetQuantumColor
           #:%PixelSetRed
           #:%PixelSetRedQuantum
           #:%PixelSetYellow
           #:%PixelSetYellowQuantum))
